import type { MenuItem, Category, User, StockItem } from './types';

export const LOW_STOCK_THRESHOLD = 10;

export const USERS: User[] = [
  { id: 'u1', pin: '1111', role: 'waiter' },
  { id: 'u2', pin: '2222', role: 'cashier' },
  { id: 'u3', pin: '3333', role: 'procurement' },
  { id: 'u4', pin: '4444', role: 'accountant' },
  { id: 'u5', pin: '5555', role: 'manager' },
  { id: 'u6', pin: '6666', role: 'director' },
];

export const STOCK_ITEMS: StockItem[] = [
  // Beverages
  { id: 'si1', name: 'Coffee Portion', quantity: 500, unit: 'pcs' },
  { id: 'si2', name: 'Milk Portion', quantity: 1000, unit: 'pcs' },
  { id: 'si3', name: 'Tea Portion', quantity: 500, unit: 'pcs' },
  { id: 'si4', name: 'Chocolate Portion', quantity: 300, unit: 'pcs' },
  { id: 'si5', name: 'Juice Base', quantity: 500, unit: 'pcs' },
  { id: 'si6', name: 'Smoothie Base', quantity: 300, unit: 'pcs' },
  { id: 'si7', name: 'Milkshake Base', quantity: 300, unit: 'pcs' },
  { id: 'si8', name: 'Mocktail Base', quantity: 400, unit: 'pcs' },
  { id: 'si9', name: 'Lemonade Base', quantity: 400, unit: 'pcs' },
  { id: 'si10', name: 'Soda 300ml', quantity: 200, unit: 'pcs' },
  { id: 'si11', name: 'Soda 500ml', quantity: 200, unit: 'pcs' },
  { id: 'si12', name: 'Water Still 300ml', quantity: 100, unit: 'pcs' },
  { id: 'si13', name: 'Water Still 500ml', quantity: 100, unit: 'pcs' },
  { id: 'si14', name: 'Water Sparkling 300ml', quantity: 100, unit: 'pcs' },
  { id: 'si15', name: 'Water Sparkling 500ml', quantity: 100, unit: 'pcs' },

  // Core Ingredients
  { id: 'si20', name: 'Egg', quantity: 500, unit: 'pcs' },
  { id: 'si21', name: 'Bread Slice', quantity: 800, unit: 'pcs' },
  { id: 'si22', name: 'Bacon Slice', quantity: 1000, unit: 'pcs' },
  { id: 'si23', name: 'Sausage Link (Beef)', quantity: 400, unit: 'pcs' },
  { id: 'si24', name: 'Potato (for chips)', quantity: 50000, unit: 'g' },
  { id: 'si25', name: 'Rice Portion', quantity: 500, unit: 'pcs' },
  { id: 'si26', name: 'Ugali Portion', quantity: 300, unit: 'pcs' },
  { id: 'si27', name: 'Salad Base', quantity: 200, unit: 'pcs' },

  // Meats & Proteins
  { id: 'si30', name: 'Burger Patty (Beef)', quantity: 200, unit: 'pcs' },
  { id: 'si31', name: 'Chicken Breast Portion', quantity: 150, unit: 'pcs' },
  { id: 'si32', name: 'Chicken Thigh Portion', quantity: 150, unit: 'pcs' },
  { id: 'si33', name: 'Chicken Wing', quantity: 500, unit: 'pcs' },
  { id: 'si34', name: 'Beef Portion', quantity: 100, unit: 'pcs' },
  { id: 'si35', name: 'Goat Meat Portion', quantity: 80, unit: 'pcs' },
  { id: 'si36', name: 'Lamb Chop', quantity: 100, unit: 'pcs' },
  { id: 'si37', name: 'Salmon Fillet', quantity: 50, unit: 'pcs' },
  { id: 'si38', name: 'Red Snapper Fillet', quantity: 50, unit: 'pcs' },
  { id: 'si39', name: 'Tilapia (Whole)', quantity: 50, unit: 'pcs' },
  { id: 'si40', name: 'Prawn Portion', quantity: 100, unit: 'pcs' },

  // Prepared Items
  { id: 'si50', name: 'Pizza Base', quantity: 100, unit: 'pcs' },
  { id: 'si51', name: 'Burger Bun', quantity: 200, unit: 'pcs' },
  { id: 'si52', name: 'Shawarma Portion', quantity: 100, unit: 'pcs' },
  { id: 'si53', name: 'Pasta Portion', quantity: 200, unit: 'pcs' },
  { id: 'si54', name: 'Pancake Portion', quantity: 100, unit: 'pcs' },
  { id: 'si55', name: 'Waffle Portion', quantity: 100, unit: 'pcs' },
  { id: 'si56', name: 'Samosa (Beef)', quantity: 200, unit: 'pcs' },
  { id: 'si57', name: 'Samosa (Spinach & Feta)', quantity: 150, unit: 'pcs' },
  { id: 'si58', name: 'Platter Base (serves 1)', quantity: 100, unit: 'pcs' },

  // Desserts & Pastries
  { id: 'si60', name: 'Dessert Slice (Cake/Tiramisu)', quantity: 150, unit: 'pcs' },
  { id: 'si61', name: 'Pastry (Croissant)', quantity: 150, unit: 'pcs' },
  { id: 'si62', name: 'Ice Cream Scoop', quantity: 500, unit: 'pcs' },
  
  // Kids Menu Specific
  { id: 'si70', name: 'Fish Finger', quantity: 200, unit: 'pcs' },
  { id: 'si71', name: 'Chicken Tender', quantity: 200, unit: 'pcs' },
];


export const MENU_ITEMS: MenuItem[] = [
  // Hot Drinks
  { id: 'hd01', name: 'Chai Latte', price: 300, category: 'Hot Drinks', recipe: [{ stockItemId: 'si3', quantity: 1 }, { stockItemId: 'si2', quantity: 1 }] },
  { id: 'hd02', name: 'Masala Tea', price: 300, category: 'Hot Drinks', recipe: [{ stockItemId: 'si3', quantity: 1 }] },
  { id: 'hd03', name: 'Kenyan Tea', price: 250, category: 'Hot Drinks', recipe: [{ stockItemId: 'si3', quantity: 1 }] },
  { id: 'hd04', name: 'Dawa Tea', price: 300, category: 'Hot Drinks', recipe: [{ stockItemId: 'si3', quantity: 1 }] },
  { id: 'hd05', name: 'Hibiscus Tea', price: 250, category: 'Hot Drinks', recipe: [{ stockItemId: 'si3', quantity: 1 }] },
  { id: 'hd06', name: 'Peppermint Tea', price: 250, category: 'Hot Drinks', recipe: [{ stockItemId: 'si3', quantity: 1 }] },
  { id: 'hd07', name: 'Sweet Peppermint Tea', price: 250, category: 'Hot Drinks', recipe: [{ stockItemId: 'si3', quantity: 1 }] },
  { id: 'hd08', name: 'Espresso (Single)', price: 150, category: 'Hot Drinks', recipe: [{ stockItemId: 'si1', quantity: 1 }] },
  { id: 'hd09', name: 'Espresso (Double)', price: 250, category: 'Hot Drinks', recipe: [{ stockItemId: 'si1', quantity: 2 }] },
  { id: 'hd10', name: 'Americano (Single)', price: 250, category: 'Hot Drinks', recipe: [{ stockItemId: 'si1', quantity: 1 }] },
  { id: 'hd11', name: 'Americano (Double)', price: 300, category: 'Hot Drinks', recipe: [{ stockItemId: 'si1', quantity: 2 }] },
  { id: 'hd12', name: 'Cappuccino (Single)', price: 300, category: 'Hot Drinks', recipe: [{ stockItemId: 'si1', quantity: 1 }, { stockItemId: 'si2', quantity: 1 }] },
  { id: 'hd13', name: 'Cappuccino (Double)', price: 400, category: 'Hot Drinks', recipe: [{ stockItemId: 'si1', quantity: 2 }, { stockItemId: 'si2', quantity: 1 }] },
  { id: 'hd14', name: 'Latte (Single)', price: 250, category: 'Hot Drinks', recipe: [{ stockItemId: 'si1', quantity: 1 }, { stockItemId: 'si2', quantity: 1 }] },
  { id: 'hd15', name: 'Latte (Double)', price: 350, category: 'Hot Drinks', recipe: [{ stockItemId: 'si1', quantity: 2 }, { stockItemId: 'si2', quantity: 1 }] },
  { id: 'hd16', name: 'Latte Macchiato (Single)', price: 300, category: 'Hot Drinks', recipe: [{ stockItemId: 'si1', quantity: 1 }, { stockItemId: 'si2', quantity: 1 }] },
  { id: 'hd17', name: 'Latte Macchiato (Double)', price: 350, category: 'Hot Drinks', recipe: [{ stockItemId: 'si1', quantity: 2 }, { stockItemId: 'si2', quantity: 1 }] },
  { id: 'hd18', name: 'Macchiato', price: 200, category: 'Hot Drinks', recipe: [{ stockItemId: 'si1', quantity: 1 }] },
  { id: 'hd19', name: 'Cortado', price: 300, category: 'Hot Drinks', recipe: [{ stockItemId: 'si1', quantity: 1 }] },
  { id: 'hd20', name: 'Flat White', price: 300, category: 'Hot Drinks', recipe: [{ stockItemId: 'si1', quantity: 1 }, { stockItemId: 'si2', quantity: 1 }] },
  { id: 'hd21', name: 'House Coffee', price: 200, category: 'Hot Drinks', recipe: [{ stockItemId: 'si1', quantity: 1 }] },
  { id: 'hd22', name: 'Hot Chocolate', price: 300, category: 'Hot Drinks', recipe: [{ stockItemId: 'si4', quantity: 1 }, { stockItemId: 'si2', quantity: 1 }] },
  { id: 'hd23', name: 'Black Chocolate', price: 250, category: 'Hot Drinks', recipe: [{ stockItemId: 'si4', quantity: 1 }] },

  // Breakfast
  { id: 'bf01', name: 'Shakshouka', price: 1150, category: 'Breakfast', recipe: [{ stockItemId: 'si20', quantity: 2 }, { stockItemId: 'si21', quantity: 2 }] },
  { id: 'bf02', name: 'Eggs Benedict', price: 980, category: 'Breakfast', recipe: [{ stockItemId: 'si20', quantity: 2 }, { stockItemId: 'si21', quantity: 2 }] },
  { id: 'bf03', name: 'Classic Breakfast', price: 800, category: 'Breakfast', recipe: [{ stockItemId: 'si20', quantity: 2 }, { stockItemId: 'si22', quantity: 2 }, { stockItemId: 'si23', quantity: 2 }] },
  { id: 'bf04', name: 'Burrata Toast', price: 970, category: 'Breakfast', recipe: [{ stockItemId: 'si21', quantity: 2 }] },
  { id: 'bf05', name: 'Avocado Eggs & Toast', price: 650, category: 'Breakfast', recipe: [{ stockItemId: 'si20', quantity: 2 }, { stockItemId: 'si21', quantity: 2 }] },
  { id: 'bf06', name: 'Mexican Omelette', price: 630, category: 'Breakfast', recipe: [{ stockItemId: 'si20', quantity: 3 }, { stockItemId: 'si21', quantity: 2 }] },
  { id: 'bf07', name: 'Plain Omelette/Scrambled', price: 570, category: 'Breakfast', recipe: [{ stockItemId: 'si20', quantity: 3 }, { stockItemId: 'si21', quantity: 2 }] },
  { id: 'bf08', name: 'On The Move', price: 600, category: 'Breakfast', recipe: [{ stockItemId: 'si20', quantity: 2 }] },
  { id: 'bf09', name: 'Business Breakfast', price: 550, category: 'Breakfast', recipe: [{ stockItemId: 'si20', quantity: 2 }] },
  { id: 'bf10', name: 'English Breakfast', price: 600, category: 'Breakfast', recipe: [{ stockItemId: 'si20', quantity: 2 }, { stockItemId: 'si23', quantity: 2 }] },
  { id: 'bf11', name: 'Suqaar', price: 600, category: 'Breakfast', recipe: [{ stockItemId: 'si34', quantity: 1 }] },
  { id: 'bf12', name: 'Liver', price: 700, category: 'Breakfast', recipe: [{ stockItemId: 'si34', quantity: 1 }] },
  { id: 'bf13', name: 'Savoury Brunch Platter', price: 1500, category: 'Breakfast', recipe: [{ stockItemId: 'si58', quantity: 2 }] },
  { id: 'bf14', name: 'Sweet Brunch Platter', price: 2000, category: 'Breakfast', recipe: [{ stockItemId: 'si58', quantity: 2 }] },
  { id: 'bf15', name: 'Pancakes', price: 650, category: 'Breakfast', recipe: [{ stockItemId: 'si54', quantity: 1 }] },
  { id: 'bf16', name: 'French Toast', price: 800, category: 'Breakfast', recipe: [{ stockItemId: 'si21', quantity: 3 }] },
  { id: 'bf17', name: 'Granola Bowl', price: 850, category: 'Breakfast', recipe: [] },
  { id: 'bf18', name: 'Waffles', price: 800, category: 'Breakfast', recipe: [{ stockItemId: 'si55', quantity: 1 }] },

  // Main Course
  { id: 'mc01', name: 'Chicken Tikka', price: 750, category: 'Main Course', recipe: [{ stockItemId: 'si31', quantity: 1 }] },
  { id: 'mc02', name: 'Chicken Biryani', price: 750, category: 'Main Course', recipe: [{ stockItemId: 'si31', quantity: 1 }, { stockItemId: 'si25', quantity: 1 }] },
  { id: 'mc03', name: 'Chicken Wings (Meal)', price: 800, category: 'Main Course', recipe: [{ stockItemId: 'si33', quantity: 6 }] },
  { id: 'mc04', name: 'Chicken Curry', price: 850, category: 'Main Course', recipe: [{ stockItemId: 'si32', quantity: 1 }, { stockItemId: 'si25', quantity: 1 }] },
  { id: 'mc05', name: 'Beef Biryani', price: 750, category: 'Main Course', recipe: [{ stockItemId: 'si34', quantity: 1 }, { stockItemId: 'si25', quantity: 1 }] },
  { id: 'mc06', name: 'Beef Pilau', price: 600, category: 'Main Course', recipe: [{ stockItemId: 'si34', quantity: 1 }, { stockItemId: 'si25', quantity: 1 }] },
  { id: 'mc07', name: 'Beef Curry', price: 850, category: 'Main Course', recipe: [{ stockItemId: 'si34', quantity: 1 }, { stockItemId: 'si25', quantity: 1 }] },
  { id: 'mc08', name: 'Arosto (Goat Meat)', price: 1000, category: 'Main Course', recipe: [{ stockItemId: 'si35', quantity: 1 }, { stockItemId: 'si25', quantity: 1 }] },
  { id: 'mc09', name: 'Lamb Chops', price: 950, category: 'Main Course', recipe: [{ stockItemId: 'si36', quantity: 3 }] },
  { id: 'mc10', name: 'Pan Roasted Salmon', price: 2000, category: 'Main Course', recipe: [{ stockItemId: 'si37', quantity: 1 }] },
  { id: 'mc11', name: 'Grilled Red Snapper', price: 1200, category: 'Main Course', recipe: [{ stockItemId: 'si38', quantity: 1 }] },
  { id: 'mc12', name: 'Fresh Tilapia (Wet)', price: 1000, category: 'Main Course', recipe: [{ stockItemId: 'si39', quantity: 1 }] },
  { id: 'mc13', name: 'Fresh Tilapia (Dry)', price: 1000, category: 'Main Course', recipe: [{ stockItemId: 'si39', quantity: 1 }] },
  { id: 'mc14', name: 'Pasta Arrabbiata', price: 1290, category: 'Main Course', recipe: [{ stockItemId: 'si53', quantity: 1 }] },
  { id: 'mc15', name: 'Mushroom Penne', price: 800, category: 'Main Course', recipe: [{ stockItemId: 'si53', quantity: 1 }] },
  { id: 'mc16', name: 'Chicken Pesto', price: 800, category: 'Main Course', recipe: [{ stockItemId: 'si53', quantity: 1 }, { stockItemId: 'si31', quantity: 1 }] },
  { id: 'mc17', name: 'Prawn Linguine Pasta', price: 1500, category: 'Main Course', recipe: [{ stockItemId: 'si53', quantity: 1 }, { stockItemId: 'si40', quantity: 1 }] },
  { id: 'mc18', name: 'Vegetarian Pasta', price: 1370, category: 'Main Course', recipe: [{ stockItemId: 'si53', quantity: 1 }] },
  { id: 'mc19', name: 'Pasta Saldato', price: 1000, category: 'Main Course', recipe: [{ stockItemId: 'si53', quantity: 1 }] },
  { id: 'mc20', name: 'Pasta Alfredo', price: 1000, category: 'Main Course', recipe: [{ stockItemId: 'si53', quantity: 1 }] },
  { id: 'mc21', name: 'Pasta Alforno', price: 1000, category: 'Main Course', recipe: [{ stockItemId: 'si53', quantity: 1 }] },
  { id: 'mc22', name: 'Pasta Palapak', price: 1000, category: 'Main Course', recipe: [{ stockItemId: 'si53', quantity: 1 }] },
  { id: 'mc23', name: 'Vegetable Curry', price: 750, category: 'Main Course', recipe: [{ stockItemId: 'si25', quantity: 1 }] },
  { id: 'mc24', name: 'Green Gram', price: 500, category: 'Main Course', recipe: [{ stockItemId: 'si25', quantity: 1 }] },
  { id: 'mc25', name: 'Mixed Vegetables', price: 500, category: 'Main Course', recipe: [] },
  { id: 'mc26', name: 'Coconut Beans', price: 500, category: 'Main Course', recipe: [{ stockItemId: 'si25', quantity: 1 }] },
  { id: 'mc27', name: 'Fried Beans', price: 500, category: 'Main Course', recipe: [{ stockItemId: 'si25', quantity: 1 }] },
  
  // Pizza & Burgers
  { id: 'pb01', name: 'Margarita Pizza', price: 900, category: 'Pizza & Burgers', recipe: [{ stockItemId: 'si50', quantity: 1 }] },
  { id: 'pb02', name: 'Pollo Pizza', price: 1000, category: 'Pizza & Burgers', recipe: [{ stockItemId: 'si50', quantity: 1 }, { stockItemId: 'si31', quantity: 1 }] },
  { id: 'pb03', name: 'Roast Veg & Feta Pizza', price: 1000, category: 'Pizza & Burgers', recipe: [{ stockItemId: 'si50', quantity: 1 }] },
  { id: 'pb04', name: 'Beef Burger', price: 1000, category: 'Pizza & Burgers', recipe: [{ stockItemId: 'si30', quantity: 1 }, { stockItemId: 'si51', quantity: 1 }] },
  { id: 'pb05', name: 'Chicken Shawarma', price: 700, category: 'Pizza & Burgers', recipe: [{ stockItemId: 'si52', quantity: 1 }] },

  // Salads & Sides
  { id: 'ss01', name: 'California Chicken Salad', price: 1000, category: 'Salads & Sides', recipe: [{ stockItemId: 'si27', quantity: 1 }, { stockItemId: 'si31', quantity: 1 }] },
  { id: 'ss02', name: 'Caesar Salad', price: 1000, category: 'Salads & Sides', recipe: [{ stockItemId: 'si27', quantity: 1 }] },
  { id: 'ss03', name: 'Vegetarian Caesar Salad', price: 1240, category: 'Salads & Sides', recipe: [{ stockItemId: 'si27', quantity: 1 }] },
  { id: 'ss04', name: 'Corn Salad', price: 800, category: 'Salads & Sides', recipe: [{ stockItemId: 'si27', quantity: 1 }] },
  { id: 'ss05', name: 'Halloumi & Avocado Salad', price: 1290, category: 'Salads & Sides', recipe: [{ stockItemId: 'si27', quantity: 1 }] },
  { id: 'ss06', name: 'Pilau (Side)', price: 250, category: 'Salads & Sides', recipe: [{ stockItemId: 'si25', quantity: 1 }] },
  { id: 'ss07', name: 'Coconut Rice', price: 250, category: 'Salads & Sides', recipe: [{ stockItemId: 'si25', quantity: 1 }] },
  { id: 'ss08', name: 'Chips', price: 200, category: 'Salads & Sides', recipe: [{ stockItemId: 'si24', quantity: 300 }] },
  { id: 'ss09', name: 'Masala Chips', price: 300, category: 'Salads & Sides', recipe: [{ stockItemId: 'si24', quantity: 300 }] },
  { id: 'ss10', name: 'Potato Wedges', price: 300, category: 'Salads & Sides', recipe: [{ stockItemId: 'si24', quantity: 300 }] },
  { id: 'ss11', name: 'Naan', price: 150, category: 'Salads & Sides', recipe: [{ stockItemId: 'si21', quantity: 1 }] },
  { id: 'ss12', name: 'Kachumbari', price: 150, category: 'Salads & Sides', recipe: [] },
  { id: 'ss13', name: 'Kale (Sukuma)', price: 200, category: 'Salads & Sides', recipe: [] },
  { id: 'ss14', name: 'Coconut Spinach', price: 200, category: 'Salads & Sides', recipe: [] },
  { id: 'ss15', name: 'Ugali', price: 200, category: 'Salads & Sides', recipe: [{ stockItemId: 'si26', quantity: 1 }] },
  { id: 'ss16', name: 'Mashed Potatoes', price: 200, category: 'Salads & Sides', recipe: [{ stockItemId: 'si24', quantity: 250 }] },
  { id: 'ss17', name: 'Ugali Wimbi', price: 200, category: 'Salads & Sides', recipe: [{ stockItemId: 'si26', quantity: 1 }] },
  { id: 'ss18', name: 'Managu', price: 200, category: 'Salads & Sides', recipe: [] },
  { id: 'ss19', name: 'Mukimo', price: 200, category: 'Salads & Sides', recipe: [] },
  { id: 'ss20', name: 'Matoke', price: 250, category: 'Salads & Sides', recipe: [] },
  { id: 'ss21', name: 'Matumbo', price: 300, category: 'Salads & Sides', recipe: [] },
  { id: 'ss22', name: 'Githeri', price: 200, category: 'Salads & Sides', recipe: [] },
  { id: 'ss23', name: 'Extra Avocado', price: 100, category: 'Salads & Sides', recipe: [] },
  { id: 'ss24', name: 'Extra 2 Boiled Eggs', price: 200, category: 'Salads & Sides', recipe: [{ stockItemId: 'si20', quantity: 2 }] },
  { id: 'ss25', name: 'Extra Grilled Chicken', price: 300, category: 'Salads & Sides', recipe: [{ stockItemId: 'si31', quantity: 1 }] },
  { id: 'ss26', name: 'Extra 2 Beef Sausages', price: 250, category: 'Salads & Sides', recipe: [{ stockItemId: 'si23', quantity: 2 }] },
  { id: 'ss27', name: 'Extra Beef Bacon', price: 250, category: 'Salads & Sides', recipe: [{ stockItemId: 'si22', quantity: 3 }] },
  { id: 'ss28', name: 'Extra Caramelised Onions', price: 120, category: 'Salads & Sides', recipe: [] },
  { id: 'ss29', name: 'Extra Cheese', price: 250, category: 'Salads & Sides', recipe: [] },
  { id: 'ss30', name: 'Extra Toast', price: 120, category: 'Salads & Sides', recipe: [{ stockItemId: 'si21', quantity: 2 }] },

  // Snacks & Platters
  { id: 'sp01', name: '4 Wings (Snack)', price: 800, category: 'Snacks & Platters', recipe: [{ stockItemId: 'si33', quantity: 4 }] },
  { id: 'sp02', name: '3 Beef Samosas', price: 300, category: 'Snacks & Platters', recipe: [{ stockItemId: 'si56', quantity: 3 }] },
  { id: 'sp03', name: '3 Spinach & Feta Samosas', price: 300, category: 'Snacks & Platters', recipe: [{ stockItemId: 'si57', quantity: 3 }] },
  { id: 'sp04', name: 'Loaded Fries', price: 1000, category: 'Snacks & Platters', recipe: [{ stockItemId: 'si24', quantity: 400 }] },
  { id: 'sp05', name: '2 Sausages & Fries', price: 650, category: 'Snacks & Platters', recipe: [{ stockItemId: 'si23', quantity: 2 }, { stockItemId: 'si24', quantity: 300 }] },
  { id: 'sp06', name: 'Platter For 2', price: 1950, category: 'Snacks & Platters', recipe: [{ stockItemId: 'si58', quantity: 2 }] },
  { id: 'sp07', name: 'Platter For 3', price: 2550, category: 'Snacks & Platters', recipe: [{ stockItemId: 'si58', quantity: 3 }] },
  { id: 'sp08', name: 'Platter For 4', price: 3550, category: 'Snacks & Platters', recipe: [{ stockItemId: 'si58', quantity: 4 }] },
  { id: 'sp09', name: 'Platter For 5', price: 4250, category: 'Snacks & Platters', recipe: [{ stockItemId: 'si58', quantity: 5 }] },
  { id: 'sp10', name: 'Platter For 6', price: 5200, category: 'Snacks & Platters', recipe: [{ stockItemId: 'si58', quantity: 6 }] },
  
  // Kids Menu
  { id: 'km01', name: 'Kids Plain Pancake', price: 570, category: 'Kids Menu', recipe: [{ stockItemId: 'si54', quantity: 1 }] },
  { id: 'km02', name: 'Kids Pancake & Eggs', price: 570, category: 'Kids Menu', recipe: [{ stockItemId: 'si54', quantity: 1 }, { stockItemId: 'si20', quantity: 1 }] },
  { id: 'km03', name: 'Kids Pancake & Beef Sausage', price: 610, category: 'Kids Menu', recipe: [{ stockItemId: 'si54', quantity: 1 }, { stockItemId: 'si23', quantity: 1 }] },
  { id: 'km04', name: 'Kids Fries & Beef Sausage', price: 340, category: 'Kids Menu', recipe: [{ stockItemId: 'si24', quantity: 150 }, { stockItemId: 'si23', quantity: 1 }] },
  { id: 'km05', name: 'Kids Chicken Tenders', price: 500, category: 'Kids Menu', recipe: [{ stockItemId: 'si71', quantity: 3 }] },
  { id: 'km06', name: 'Kids Fish Fingers', price: 500, category: 'Kids Menu', recipe: [{ stockItemId: 'si70', quantity: 4 }] },
  { id: 'km07', name: 'Kids Grilled Cheese', price: 640, category: 'Kids Menu', recipe: [{ stockItemId: 'si21', quantity: 2 }] },
  { id: 'km08', name: 'Kids Cheese Burger', price: 640, category: 'Kids Menu', recipe: [{ stockItemId: 'si30', quantity: 1 }, { stockItemId: 'si51', quantity: 1 }] },
  { id: 'km09', name: 'Kids Strawberry Milk', price: 200, category: 'Kids Menu', recipe: [{ stockItemId: 'si2', quantity: 1 }] },
  { id: 'km10', name: 'Kids Chocolate Milk', price: 200, category: 'Kids Menu', recipe: [{ stockItemId: 'si2', quantity: 1 }] },
  { id: 'km11', name: 'Kids Hot Chocolate', price: 220, category: 'Kids Menu', recipe: [{ stockItemId: 'si4', quantity: 1 }] },
  { id: 'km12', name: 'Kids Vanilla Milk', price: 200, category: 'Kids Menu', recipe: [{ stockItemId: 'si2', quantity: 1 }] },
  { id: 'km13', name: 'Kids Vanilla & Banana Smoothie', price: 300, category: 'Kids Menu', recipe: [{ stockItemId: 'si6', quantity: 1 }] },
  { id: 'km14', name: 'Kids Strawberry Smoothie', price: 300, category: 'Kids Menu', recipe: [{ stockItemId: 'si6', quantity: 1 }] },
  { id: 'km15', name: 'Kids Tropical Smoothie', price: 300, category: 'Kids Menu', recipe: [{ stockItemId: 'si6', quantity: 1 }] },
  { id: 'km16', name: 'Kids Fruit Mashup & Ice Cream', price: 420, category: 'Kids Menu', recipe: [{ stockItemId: 'si62', quantity: 1 }] },
  { id: 'km17', name: 'Kids Chocolate Ice Cream', price: 210, category: 'Kids Menu', recipe: [{ stockItemId: 'si62', quantity: 1 }] },
  { id: 'km18', name: 'Kids Vanilla Ice Cream', price: 210, category: 'Kids Menu', recipe: [{ stockItemId: 'si62', quantity: 1 }] },

  // Desserts & Pastries
  { id: 'dp01', name: 'Tiramisu', price: 490, category: 'Desserts & Pastries', recipe: [{ stockItemId: 'si60', quantity: 1 }] },
  { id: 'dp02', name: 'Date Cake', price: 590, category: 'Desserts & Pastries', recipe: [{ stockItemId: 'si60', quantity: 1 }] },
  { id: 'dp03', name: 'Umm Ali', price: 590, category: 'Desserts & Pastries', recipe: [{ stockItemId: 'si60', quantity: 1 }] },
  { id: 'dp04', name: 'Brownie Cheesecake', price: 590, category: 'Desserts & Pastries', recipe: [{ stockItemId: 'si60', quantity: 1 }] },
  { id: 'dp05', name: 'Butter Croissant', price: 250, category: 'Desserts & Pastries', recipe: [{ stockItemId: 'si61', quantity: 1 }] },
  { id: 'dp06', name: 'Almond Croissant', price: 250, category: 'Desserts & Pastries', recipe: [{ stockItemId: 'si61', quantity: 1 }] },
  { id: 'dp07', name: 'Chocolate Croissant', price: 200, category: 'Desserts & Pastries', recipe: [{ stockItemId: 'si61', quantity: 1 }] },
  { id: 'dp08', name: 'Carrot Cake', price: 300, category: 'Desserts & Pastries', recipe: [{ stockItemId: 'si60', quantity: 1 }] },
  { id: 'dp09', name: 'Black Forest Cake', price: 300, category: 'Desserts & Pastries', recipe: [{ stockItemId: 'si60', quantity: 1 }] },
  { id: 'dp10', name: 'Ice Cream (Vanilla, Single)', price: 250, category: 'Desserts & Pastries', recipe: [{ stockItemId: 'si62', quantity: 1 }] },
  { id: 'dp11', name: 'Ice Cream (Vanilla, Double)', price: 450, category: 'Desserts & Pastries', recipe: [{ stockItemId: 'si62', quantity: 2 }] },
  { id: 'dp12', name: 'Ice Cream (Chocolate, Single)', price: 250, category: 'Desserts & Pastries', recipe: [{ stockItemId: 'si62', quantity: 1 }] },
  { id: 'dp13', name: 'Ice Cream (Chocolate, Double)', price: 450, category: 'Desserts & Pastries', recipe: [{ stockItemId: 'si62', quantity: 2 }] },
  { id: 'dp14', name: 'Ice Cream (Strawberry, Single)', price: 250, category: 'Desserts & Pastries', recipe: [{ stockItemId: 'si62', quantity: 1 }] },
  { id: 'dp15', name: 'Ice Cream (Strawberry, Double)', price: 450, category: 'Desserts & Pastries', recipe: [{ stockItemId: 'si62', quantity: 2 }] },
  
  // Cold Drinks
  { id: 'cd01', name: 'Berry me Mojito', price: 600, category: 'Cold Drinks', recipe: [{ stockItemId: 'si8', quantity: 1 }] },
  { id: 'cd02', name: 'Kiwi Mojito', price: 600, category: 'Cold Drinks', recipe: [{ stockItemId: 'si8', quantity: 1 }] },
  { id: 'cd03', name: 'Blueberry Mojito', price: 600, category: 'Cold Drinks', recipe: [{ stockItemId: 'si8', quantity: 1 }] },
  { id: 'cd04', name: 'Passion Mojito', price: 600, category: 'Cold Drinks', recipe: [{ stockItemId: 'si8', quantity: 1 }] },
  { id: 'cd05', name: 'Peach Mojito', price: 600, category: 'Cold Drinks', recipe: [{ stockItemId: 'si8', quantity: 1 }] },
  { id: 'cd06', name: 'Mint Lemonade', price: 450, category: 'Cold Drinks', recipe: [{ stockItemId: 'si9', quantity: 1 }] },
  { id: 'cd07', name: 'Passion Lemonade', price: 450, category: 'Cold Drinks', recipe: [{ stockItemId: 'si9', quantity: 1 }] },
  { id: 'cd08', name: 'Classic Lemonade', price: 450, category: 'Cold Drinks', recipe: [{ stockItemId: 'si9', quantity: 1 }] },
  { id: 'cd09', name: 'Strawberry Lemonade', price: 450, category: 'Cold Drinks', recipe: [{ stockItemId: 'si9', quantity: 1 }] },
  { id: 'cd10', name: 'Blueberry Lemonade', price: 450, category: 'Cold Drinks', recipe: [{ stockItemId: 'si9', quantity: 1 }] },
  { id: 'cd11', name: 'Peach Lemonade', price: 450, category: 'Cold Drinks', recipe: [{ stockItemId: 'si9', quantity: 1 }] },
  { id: 'cd12', name: 'Kiwi Lemonade', price: 450, category: 'Cold Drinks', recipe: [{ stockItemId: 'si9', quantity: 1 }] },
  { id: 'cd13', name: 'Tropical Smoothie', price: 550, category: 'Cold Drinks', recipe: [{ stockItemId: 'si6', quantity: 1 }] },
  { id: 'cd14', name: 'Blueberry Smoothie', price: 550, category: 'Cold Drinks', recipe: [{ stockItemId: 'si6', quantity: 1 }] },
  { id: 'cd15', name: 'Banana Mango Smoothie', price: 550, category: 'Cold Drinks', recipe: [{ stockItemId: 'si6', quantity: 1 }] },
  { id: 'cd16', name: 'Strawberry Smoothie', price: 550, category: 'Cold Drinks', recipe: [{ stockItemId: 'si6', quantity: 1 }] },
  { id: 'cd17', name: 'Avocado Shake', price: 550, category: 'Cold Drinks', recipe: [{ stockItemId: 'si7', quantity: 1 }] },
  { id: 'cd18', name: 'Tropical Shake', price: 550, category: 'Cold Drinks', recipe: [{ stockItemId: 'si7', quantity: 1 }] },
  { id: 'cd19', name: 'Hydrabad Shake', price: 550, category: 'Cold Drinks', recipe: [{ stockItemId: 'si7', quantity: 1 }] },
  { id: 'cd20', name: 'Datte Shake', price: 550, category: 'Cold Drinks', recipe: [{ stockItemId: 'si7', quantity: 1 }] },
  { id: 'cd21', name: 'Espresso Shake', price: 550, category: 'Cold Drinks', recipe: [{ stockItemId: 'si7', quantity: 1 }, { stockItemId: 'si1', quantity: 1 }] },
  { id: 'cd22', name: 'Pineapple Juice', price: 400, category: 'Cold Drinks', recipe: [{ stockItemId: 'si5', quantity: 1 }] },
  { id: 'cd23', name: 'Water Melon Juice', price: 400, category: 'Cold Drinks', recipe: [{ stockItemId: 'si5', quantity: 1 }] },
  { id: 'cd24', name: 'Passion Juice', price: 400, category: 'Cold Drinks', recipe: [{ stockItemId: 'si5', quantity: 1 }] },
  { id: 'cd25', name: 'Cocktail Juice', price: 400, category: 'Cold Drinks', recipe: [{ stockItemId: 'si5', quantity: 1 }] },
  { id: 'cd26', name: 'Orange Juice', price: 400, category: 'Cold Drinks', recipe: [{ stockItemId: 'si5', quantity: 1 }] },
  { id: 'cd27', name: 'Pineapple Mint Juice', price: 450, category: 'Cold Drinks', recipe: [{ stockItemId: 'si5', quantity: 1 }] },
  { id: 'cd28', name: 'Water (Still, 300ml)', price: 150, category: 'Cold Drinks', recipe: [{ stockItemId: 'si12', quantity: 1 }] },
  { id: 'cd29', name: 'Water (Still, 500ml)', price: 250, category: 'Cold Drinks', recipe: [{ stockItemId: 'si13', quantity: 1 }] },
  { id: 'cd30', name: 'Water (Sparkling, 300ml)', price: 110, category: 'Cold Drinks', recipe: [{ stockItemId: 'si14', quantity: 1 }] },
  { id: 'cd31', name: 'Water (Sparkling, 500ml)', price: 170, category: 'Cold Drinks', recipe: [{ stockItemId: 'si15', quantity: 1 }] },
  { id: 'cd32', name: 'Soda (300ml)', price: 100, category: 'Cold Drinks', recipe: [{ stockItemId: 'si10', quantity: 1 }] },
  { id: 'cd33', name: 'Soda (500ml)', price: 150, category: 'Cold Drinks', recipe: [{ stockItemId: 'si11', quantity: 1 }] },
  { id: 'cd34', name: 'Iced Americano', price: 350, category: 'Cold Drinks', recipe: [{ stockItemId: 'si1', quantity: 1 }] },
  { id: 'cd35', name: 'Iced Cappuccino', price: 350, category: 'Cold Drinks', recipe: [{ stockItemId: 'si1', quantity: 1 }, { stockItemId: 'si2', quantity: 1 }] },
  { id: 'cd36', name: 'Iced Latte', price: 350, category: 'Cold Drinks', recipe: [{ stockItemId: 'si1', quantity: 1 }, { stockItemId: 'si2', quantity: 1 }] },
  { id: 'cd37', name: 'Strawberry Iced Tea', price: 350, category: 'Cold Drinks', recipe: [{ stockItemId: 'si3', quantity: 1 }] },
  { id: 'cd38', name: 'Passion Iced Tea', price: 350, category: 'Cold Drinks', recipe: [{ stockItemId: 'si3', quantity: 1 }] },
  { id: 'cd39', name: 'Vanilla Iced Tea', price: 350, category: 'Cold Drinks', recipe: [{ stockItemId: 'si3', quantity: 1 }] },
];

export const CATEGORIES: Category[] = [
  'Hot Drinks',
  'Cold Drinks',
  'Breakfast',
  'Main Course',
  'Pizza & Burgers',
  'Salads & Sides',
  'Snacks & Platters',
  'Kids Menu',
  'Desserts & Pastries',
];
