import type { MenuItem, Category, User, StockItem } from './types';

export const LOW_STOCK_THRESHOLD = 10;

export const USERS: User[] = [
  { id: 'u1', pin: '1111', role: 'waiter' },
  { id: 'u2', pin: '2222', role: 'cashier' },
  { id: 'u3', pin: '3333', role: 'procurement' },
  { id: 'u4', pin: '4444', role: 'accountant' },
  { id: 'u5', pin: '5555', role: 'manager' },
  { id: 'u6', pin: '6666', role: 'director' },
];

export const STOCK_ITEMS: StockItem[] = [
  // Beverages & Drinks
  { id: 'si_coffee_beans', name: 'Coffee Beans', quantity: 5000, unit: 'g' },
  { id: 'si_tea_leaves', name: 'Tea Leaves', quantity: 2000, unit: 'g' },
  { id: 'si_milk', name: 'Milk', quantity: 20000, unit: 'ml' },
  { id: 'si_chocolate_powder', name: 'Chocolate Powder', quantity: 3000, unit: 'g' },
  { id: 'si_juice_base', name: 'Juice Base', quantity: 100, unit: 'pcs' },
  { id: 'si_smoothie_base', name: 'Smoothie Base', quantity: 100, unit: 'pcs' },
  { id: 'si_milkshake_base', name: 'Milkshake Base', quantity: 100, unit: 'pcs' },
  { id: 'si_mojito_base', name: 'Mojito Base', quantity: 100, unit: 'pcs' },
  { id: 'si_lemonade_base', name: 'Lemonade Base', quantity: 100, unit: 'pcs' },
  { id: 'si_soda_300', name: 'Soda 300ml', quantity: 200, unit: 'pcs' },
  { id: 'si_soda_500', name: 'Soda 500ml', quantity: 200, unit: 'pcs' },
  { id: 'si_water_still_300', name: 'Water Still 300ml', quantity: 100, unit: 'pcs' },
  { id: 'si_water_still_500', name: 'Water Still 500ml', quantity: 100, unit: 'pcs' },
  { id: 'si_water_sparkling_300', name: 'Water Sparkling 300ml', quantity: 100, unit: 'pcs' },
  { id: 'si_water_sparkling_500', name: 'Water Sparkling 500ml', quantity: 100, unit: 'pcs' },
  
  // Core Ingredients
  { id: 'si_egg', name: 'Egg', quantity: 500, unit: 'pcs' },
  { id: 'si_bread_slice', name: 'Bread Slice', quantity: 800, unit: 'pcs' },
  { id: 'si_bacon_slice', name: 'Bacon Slice', quantity: 1000, unit: 'pcs' },
  { id: 'si_sausage_beef', name: 'Sausage (Beef)', quantity: 400, unit: 'pcs' },
  { id: 'si_potato', name: 'Potato', quantity: 50000, unit: 'g' },
  { id: 'si_rice', name: 'Rice Portion', quantity: 500, unit: 'pcs' },
  { id: 'si_ugali_flour', name: 'Ugali Flour Portion', quantity: 300, unit: 'pcs' },
  { id: 'si_salad_base', name: 'Salad Base', quantity: 200, unit: 'pcs' },
  { id: 'si_tomato', name: 'Tomato', quantity: 10000, unit: 'g' },
  { id: 'si_onion', name: 'Onion', quantity: 10000, unit: 'g' },
  { id: 'si_avocado', name: 'Avocado', quantity: 100, unit: 'pcs' },
  { id: 'si_cheese', name: 'Cheese Slice/Portion', quantity: 500, unit: 'pcs' },
  
  // Meats & Proteins
  { id: 'si_burger_patty_beef', name: 'Burger Patty (Beef)', quantity: 200, unit: 'pcs' },
  { id: 'si_chicken_breast', name: 'Chicken Breast Portion', quantity: 150, unit: 'pcs' },
  { id: 'si_chicken_thighs', name: 'Chicken Thighs Portion', quantity: 150, unit: 'pcs' },
  { id: 'si_chicken_wings', name: 'Chicken Wing', quantity: 500, unit: 'pcs' },
  { id: 'si_beef_cubes', name: 'Beef Cubes Portion', quantity: 100, unit: 'pcs' },
  { id: 'si_goat_meat', name: 'Goat Meat Portion', quantity: 80, unit: 'pcs' },
  { id: 'si_lamb_chops', name: 'Lamb Chop', quantity: 100, unit: 'pcs' },
  { id: 'si_salmon_fillet', name: 'Salmon Fillet', quantity: 50, unit: 'pcs' },
  { id: 'si_red_snapper', name: 'Red Snapper Fillet', quantity: 50, unit: 'pcs' },
  { id: 'si_tilapia_whole', name: 'Tilapia (Whole)', quantity: 50, unit: 'pcs' },
  { id: 'si_prawns', name: 'Prawn Portion', quantity: 100, unit: 'pcs' },
  
  // Prepared & Bakery
  { id: 'si_pizza_base', name: 'Pizza Base', quantity: 100, unit: 'pcs' },
  { id: 'si_burger_bun', name: 'Burger Bun', quantity: 200, unit: 'pcs' },
  { id: 'si_shawarma_bread', name: 'Shawarma Bread', quantity: 100, unit: 'pcs' },
  { id: 'si_pasta_portion', name: 'Pasta Portion', quantity: 200, unit: 'pcs' },
  { id: 'si_pancake_mix', name: 'Pancake Mix Portion', quantity: 100, unit: 'pcs' },
  { id: 'si_waffle_mix', name: 'Waffle Mix Portion', quantity: 100, unit: 'pcs' },
  { id: 'si_samosa_beef', name: 'Samosa (Beef, frozen)', quantity: 200, unit: 'pcs' },
  { id: 'si_samosa_veg', name: 'Samosa (Spinach & Feta, frozen)', quantity: 150, unit: 'pcs' },
  { id: 'si_platter_base', name: 'Platter Base (serves 1)', quantity: 100, unit: 'pcs' },
  
  // Desserts & Pastries
  { id: 'si_dessert_slice', name: 'Dessert Slice (Cake/Tiramisu)', quantity: 150, unit: 'pcs' },
  { id: 'si_croissant', name: 'Croissant', quantity: 150, unit: 'pcs' },
  { id: 'si_ice_cream_scoop', name: 'Ice Cream Scoop', quantity: 500, unit: 'pcs' },
  
  // Kids Menu Specific
  { id: 'si_fish_finger', name: 'Fish Finger', quantity: 200, unit: 'pcs' },
  { id: 'si_chicken_tender', name: 'Chicken Tender', quantity: 200, unit: 'pcs' },
];


export const CATEGORIES: Category[] = [
  'Hot Drinks',
  'Cold Drinks',
  'Breakfast',
  'Main Course',
  'Burgers & Pizza',
  'Salads',
  'Snacks & Sides',
  'Platters',
  'Desserts & Pastries',
  'Kids Menu',
];


export const MENU_ITEMS: MenuItem[] = [
  // Hot Drinks
  { id: 'hd01', name: 'Chai Latte', price: 300, category: 'Hot Drinks', recipe: [{ stockItemId: 'si_tea_leaves', quantity: 5 }, { stockItemId: 'si_milk', quantity: 150 }] },
  { id: 'hd02', name: 'Masala Tea', price: 300, category: 'Hot Drinks', recipe: [{ stockItemId: 'si_tea_leaves', quantity: 5 }] },
  { id: 'hd03', name: 'Kenyan Tea', price: 250, category: 'Hot Drinks', recipe: [{ stockItemId: 'si_tea_leaves', quantity: 5 }] },
  { id: 'hd04', name: 'Dawa Tea', price: 300, category: 'Hot Drinks', recipe: [{ stockItemId: 'si_tea_leaves', quantity: 5 }] },
  { id: 'hd05', name: 'Hibiscus Tea', price: 250, category: 'Hot Drinks', recipe: [{ stockItemId: 'si_tea_leaves', quantity: 5 }] },
  { id: 'hd06', name: 'Peppermint Tea', price: 250, category: 'Hot Drinks', recipe: [{ stockItemId: 'si_tea_leaves', quantity: 5 }] },
  { id: 'hd07', name: 'Sweet Peppermint Tea', price: 250, category: 'Hot Drinks', recipe: [{ stockItemId: 'si_tea_leaves', quantity: 5 }] },
  { id: 'hd08', name: 'Espresso (Single)', price: 150, category: 'Hot Drinks', recipe: [{ stockItemId: 'si_coffee_beans', quantity: 10 }] },
  { id: 'hd09', name: 'Espresso (Double)', price: 250, category: 'Hot Drinks', recipe: [{ stockItemId: 'si_coffee_beans', quantity: 20 }] },
  { id: 'hd10', name: 'Americano (Single)', price: 250, category: 'Hot Drinks', recipe: [{ stockItemId: 'si_coffee_beans', quantity: 10 }] },
  { id: 'hd11', name: 'Americano (Double)', price: 300, category: 'Hot Drinks', recipe: [{ stockItemId: 'si_coffee_beans', quantity: 20 }] },
  { id: 'hd12', name: 'Cappuccino (Single)', price: 300, category: 'Hot Drinks', recipe: [{ stockItemId: 'si_coffee_beans', quantity: 10 }, { stockItemId: 'si_milk', quantity: 100 }] },
  { id: 'hd13', name: 'Cappuccino (Double)', price: 400, category: 'Hot Drinks', recipe: [{ stockItemId: 'si_coffee_beans', quantity: 20 }, { stockItemId: 'si_milk', quantity: 150 }] },
  { id: 'hd14', name: 'Latte (Single)', price: 250, category: 'Hot Drinks', recipe: [{ stockItemId: 'si_coffee_beans', quantity: 10 }, { stockItemId: 'si_milk', quantity: 150 }] },
  { id: 'hd15', name: 'Latte (Double)', price: 350, category: 'Hot Drinks', recipe: [{ stockItemId: 'si_coffee_beans', quantity: 20 }, { stockItemId: 'si_milk', quantity: 200 }] },
  { id: 'hd16', name: 'Latte Macchiato (Single)', price: 300, category: 'Hot Drinks', recipe: [{ stockItemId: 'si_coffee_beans', quantity: 10 }, { stockItemId: 'si_milk', quantity: 150 }] },
  { id: 'hd17', name: 'Latte Macchiato (Double)', price: 350, category: 'Hot Drinks', recipe: [{ stockItemId: 'si_coffee_beans', quantity: 20 }, { stockItemId: 'si_milk', quantity: 200 }] },
  { id: 'hd18', name: 'Macchiato', price: 200, category: 'Hot Drinks', recipe: [{ stockItemId: 'si_coffee_beans', quantity: 10 }] },
  { id: 'hd19', name: 'Cortado', price: 300, category: 'Hot Drinks', recipe: [{ stockItemId: 'si_coffee_beans', quantity: 15 }] },
  { id: 'hd20', name: 'Flat White', price: 300, category: 'Hot Drinks', recipe: [{ stockItemId: 'si_coffee_beans', quantity: 15 }, { stockItemId: 'si_milk', quantity: 100 }] },
  { id: 'hd21', name: 'House Coffee', price: 200, category: 'Hot Drinks', recipe: [{ stockItemId: 'si_coffee_beans', quantity: 10 }] },
  { id: 'hd22', name: 'Hot Chocolate', price: 300, category: 'Hot Drinks', recipe: [{ stockItemId: 'si_chocolate_powder', quantity: 20 }, { stockItemId: 'si_milk', quantity: 200 }] },
  { id: 'hd23', name: 'Black Chocolate', price: 250, category: 'Hot Drinks', recipe: [{ stockItemId: 'si_chocolate_powder', quantity: 20 }] },

  // Breakfast
  { id: 'bf01', name: 'Shakshouka', price: 1150, category: 'Breakfast', recipe: [{ stockItemId: 'si_egg', quantity: 2 }, { stockItemId: 'si_bread_slice', quantity: 2 }, { stockItemId: 'si_tomato', quantity: 150 }] },
  { id: 'bf02', name: 'Eggs Benedict', price: 980, category: 'Breakfast', recipe: [{ stockItemId: 'si_egg', quantity: 2 }, { stockItemId: 'si_bread_slice', quantity: 2 }] },
  { id: 'bf03', name: 'Classic Breakfast', price: 800, category: 'Breakfast', recipe: [{ stockItemId: 'si_egg', quantity: 2 }, { stockItemId: 'si_bacon_slice', quantity: 2 }, { stockItemId: 'si_sausage_beef', quantity: 2 }] },
  { id: 'bf04', name: 'Burrata Toast', price: 970, category: 'Breakfast', recipe: [{ stockItemId: 'si_bread_slice', quantity: 2 }, { stockItemId: 'si_cheese', quantity: 1 }] },
  { id: 'bf05', name: 'Avocado Eggs & Toast', price: 650, category: 'Breakfast', recipe: [{ stockItemId: 'si_egg', quantity: 2 }, { stockItemId: 'si_bread_slice', quantity: 2 }, { stockItemId: 'si_avocado', quantity: 1 }] },
  { id: 'bf06', name: 'Mexican Omelette', price: 630, category: 'Breakfast', recipe: [{ stockItemId: 'si_egg', quantity: 3 }, { stockItemId: 'si_bread_slice', quantity: 2 }] },
  { id: 'bf07', name: 'Plain Omelette/Scrambled', price: 570, category: 'Breakfast', recipe: [{ stockItemId: 'si_egg', quantity: 3 }, { stockItemId: 'si_bread_slice', quantity: 2 }] },
  { id: 'bf08', name: 'On The Move', price: 600, category: 'Breakfast', recipe: [{ stockItemId: 'si_egg', quantity: 2 }, { stockItemId: 'si_potato', quantity: 100 }] },
  { id: 'bf09', name: 'Business Breakfast', price: 550, category: 'Breakfast', recipe: [{ stockItemId: 'si_egg', quantity: 2 }, { stockItemId: 'si_sausage_beef', quantity: 1 }] },
  { id: 'bf10', name: 'English Breakfast', price: 600, category: 'Breakfast', recipe: [{ stockItemId: 'si_egg', quantity: 2 }, { stockItemId: 'si_sausage_beef', quantity: 2 }, { stockItemId: 'si_bread_slice', quantity: 2 }] },
  { id: 'bf11', name: 'Suqaar', price: 600, category: 'Breakfast', recipe: [{ stockItemId: 'si_beef_cubes', quantity: 1 }] },
  { id: 'bf12', name: 'Liver', price: 700, category: 'Breakfast', recipe: [{ stockItemId: 'si_beef_cubes', quantity: 1 }] },
  { id: 'bf13', name: 'Pancakes', price: 650, category: 'Breakfast', recipe: [{ stockItemId: 'si_pancake_mix', quantity: 1 }] },
  { id: 'bf14', name: 'French Toast', price: 800, category: 'Breakfast', recipe: [{ stockItemId: 'si_bread_slice', quantity: 3 }] },
  { id: 'bf15', name: 'Granola Bowl', price: 850, category: 'Breakfast', recipe: [] },
  { id: 'bf16', name: 'Waffles', price: 800, category: 'Breakfast', recipe: [{ stockItemId: 'si_waffle_mix', quantity: 1 }] },

  // Main Course
  { id: 'mc01', name: 'Chicken Tikka', price: 750, category: 'Main Course', recipe: [{ stockItemId: 'si_chicken_breast', quantity: 1 }] },
  { id: 'mc02', name: 'Chicken Biryani', price: 750, category: 'Main Course', recipe: [{ stockItemId: 'si_chicken_breast', quantity: 1 }, { stockItemId: 'si_rice', quantity: 1 }] },
  { id: 'mc03', name: 'Chicken Wings (Meal)', price: 800, category: 'Main Course', recipe: [{ stockItemId: 'si_chicken_wings', quantity: 6 }] },
  { id: 'mc04', name: 'Chicken Curry', price: 850, category: 'Main Course', recipe: [{ stockItemId: 'si_chicken_thighs', quantity: 1 }, { stockItemId: 'si_rice', quantity: 1 }] },
  { id: 'mc05', name: 'Beef Biryani', price: 750, category: 'Main Course', recipe: [{ stockItemId: 'si_beef_cubes', quantity: 1 }, { stockItemId: 'si_rice', quantity: 1 }] },
  { id: 'mc06', name: 'Beef Pilau', price: 600, category: 'Main Course', recipe: [{ stockItemId: 'si_beef_cubes', quantity: 1 }, { stockItemId: 'si_rice', quantity: 1 }] },
  { id: 'mc07', name: 'Beef Curry', price: 850, category: 'Main Course', recipe: [{ stockItemId: 'si_beef_cubes', quantity: 1 }, { stockItemId: 'si_rice', quantity: 1 }] },
  { id: 'mc08', name: 'Arosto (Goat Meat)', price: 1000, category: 'Main Course', recipe: [{ stockItemId: 'si_goat_meat', quantity: 1 }, { stockItemId: 'si_rice', quantity: 1 }] },
  { id: 'mc09', name: 'Lamb Chops', price: 950, category: 'Main Course', recipe: [{ stockItemId: 'si_lamb_chops', quantity: 3 }] },
  { id: 'mc10', name: 'Pan Roasted Salmon', price: 2000, category: 'Main Course', recipe: [{ stockItemId: 'si_salmon_fillet', quantity: 1 }] },
  { id: 'mc11', name: 'Grilled Red Snapper', price: 1200, category: 'Main Course', recipe: [{ stockItemId: 'si_red_snapper', quantity: 1 }] },
  { id: 'mc12', name: 'Fresh Tilapia (Wet)', price: 1000, category: 'Main Course', recipe: [{ stockItemId: 'si_tilapia_whole', quantity: 1 }] },
  { id: 'mc13', name: 'Fresh Tilapia (Dry)', price: 1000, category: 'Main Course', recipe: [{ stockItemId: 'si_tilapia_whole', quantity: 1 }] },
  { id: 'mc14', name: 'Pasta Arrabbiata', price: 1290, category: 'Main Course', recipe: [{ stockItemId: 'si_pasta_portion', quantity: 1 }] },
  { id: 'mc15', name: 'Mushroom Penne', price: 800, category: 'Main Course', recipe: [{ stockItemId: 'si_pasta_portion', quantity: 1 }] },
  { id: 'mc16', name: 'Chicken Pesto', price: 800, category: 'Main Course', recipe: [{ stockItemId: 'si_pasta_portion', quantity: 1 }, { stockItemId: 'si_chicken_breast', quantity: 1 }] },
  { id: 'mc17', name: 'Prawn Linguine Pasta', price: 1500, category: 'Main Course', recipe: [{ stockItemId: 'si_pasta_portion', quantity: 1 }, { stockItemId: 'si_prawns', quantity: 1 }] },
  { id: 'mc18', name: 'Vegetarian Pasta', price: 1370, category: 'Main Course', recipe: [{ stockItemId: 'si_pasta_portion', quantity: 1 }] },
  { id: 'mc19', name: 'Pasta Saldato', price: 1000, category: 'Main Course', recipe: [{ stockItemId: 'si_pasta_portion', quantity: 1 }] },
  { id: 'mc20', name: 'Pasta Alfredo', price: 1000, category: 'Main Course', recipe: [{ stockItemId: 'si_pasta_portion', quantity: 1 }] },
  { id: 'mc21', name: 'Pasta Alforno', price: 1000, category: 'Main Course', recipe: [{ stockItemId: 'si_pasta_portion', quantity: 1 }] },
  { id: 'mc22', name: 'Pasta Palapak', price: 1000, category: 'Main Course', recipe: [{ stockItemId: 'si_pasta_portion', quantity: 1 }] },
  { id: 'mc23', name: 'Vegetable Curry', price: 750, category: 'Main Course', recipe: [{ stockItemId: 'si_rice', quantity: 1 }] },
  { id: 'mc24', name: 'Green Gram', price: 500, category: 'Main Course', recipe: [{ stockItemId: 'si_rice', quantity: 1 }] },
  { id: 'mc25', name: 'Mixed Vegetables', price: 500, category: 'Main Course', recipe: [] },
  { id: 'mc26', name: 'Coconut Beans', price: 500, category: 'Main Course', recipe: [{ stockItemId: 'si_rice', quantity: 1 }] },
  { id: 'mc27', name: 'Fried Beans', price: 500, category: 'Main Course', recipe: [{ stockItemId: 'si_rice', quantity: 1 }] },
  
  // Burgers & Pizza
  { id: 'bp01', name: 'Margarita Pizza', price: 900, category: 'Burgers & Pizza', recipe: [{ stockItemId: 'si_pizza_base', quantity: 1 }] },
  { id: 'bp02', name: 'Pollo Pizza', price: 1000, category: 'Burgers & Pizza', recipe: [{ stockItemId: 'si_pizza_base', quantity: 1 }, { stockItemId: 'si_chicken_breast', quantity: 1 }] },
  { id: 'bp03', name: 'Roast Veg & Feta Pizza', price: 1000, category: 'Burgers & Pizza', recipe: [{ stockItemId: 'si_pizza_base', quantity: 1 }] },
  { id: 'bp04', name: 'Beef Burger', price: 1000, category: 'Burgers & Pizza', recipe: [{ stockItemId: 'si_burger_patty_beef', quantity: 1 }, { stockItemId: 'si_burger_bun', quantity: 1 }, { stockItemId: 'si_potato', quantity: 200 }] },
  { id: 'bp05', name: 'Chicken Shawarma', price: 700, category: 'Burgers & Pizza', recipe: [{ stockItemId: 'si_shawarma_bread', quantity: 1 }, { stockItemId: 'si_chicken_thighs', quantity: 1 }, { stockItemId: 'si_potato', quantity: 200 }] },

  // Salads
  { id: 'sl01', name: 'California Chicken Salad', price: 1000, category: 'Salads', recipe: [{ stockItemId: 'si_salad_base', quantity: 1 }, { stockItemId: 'si_chicken_breast', quantity: 1 }] },
  { id: 'sl02', name: 'Caesar Salad', price: 1000, category: 'Salads', recipe: [{ stockItemId: 'si_salad_base', quantity: 1 }] },
  { id: 'sl03', name: 'Vegetarian Caesar Salad', price: 1240, category: 'Salads', recipe: [{ stockItemId: 'si_salad_base', quantity: 1 }] },
  { id: 'sl04', name: 'Corn Salad', price: 800, category: 'Salads', recipe: [{ stockItemId: 'si_salad_base', quantity: 1 }] },
  { id: 'sl05', name: 'Halloumi & Avocado Salad', price: 1290, category: 'Salads', recipe: [{ stockItemId: 'si_salad_base', quantity: 1 }, { stockItemId: 'si_avocado', quantity: 1 }] },

  // Snacks & Sides
  { id: 'ss01', name: '4 Wings (Snack)', price: 800, category: 'Snacks & Sides', recipe: [{ stockItemId: 'si_chicken_wings', quantity: 4 }] },
  { id: 'ss02', name: '3 Beef Samosas', price: 300, category: 'Snacks & Sides', recipe: [{ stockItemId: 'si_samosa_beef', quantity: 3 }] },
  { id: 'ss03', name: '3 Spinach & Feta Samosas', price: 300, category: 'Snacks & Sides', recipe: [{ stockItemId: 'si_samosa_veg', quantity: 3 }] },
  { id: 'ss04', name: 'Loaded Fries', price: 1000, category: 'Snacks & Sides', recipe: [{ stockItemId: 'si_potato', quantity: 400 }] },
  { id: 'ss05', name: '2 Sausages & Fries', price: 650, category: 'Snacks & Sides', recipe: [{ stockItemId: 'si_sausage_beef', quantity: 2 }, { stockItemId: 'si_potato', quantity: 300 }] },
  { id: 'ss06', name: 'Pilau (Side)', price: 250, category: 'Snacks & Sides', recipe: [{ stockItemId: 'si_rice', quantity: 1 }] },
  { id: 'ss07', name: 'Coconut Rice', price: 250, category: 'Snacks & Sides', recipe: [{ stockItemId: 'si_rice', quantity: 1 }] },
  { id: 'ss08', name: 'Chips', price: 200, category: 'Snacks & Sides', recipe: [{ stockItemId: 'si_potato', quantity: 300 }] },
  { id: 'ss09', name: 'Masala Chips', price: 300, category: 'Snacks & Sides', recipe: [{ stockItemId: 'si_potato', quantity: 300 }] },
  { id: 'ss10', name: 'Potato Wedges', price: 300, category: 'Snacks & Sides', recipe: [{ stockItemId: 'si_potato', quantity: 300 }] },
  { id: 'ss11', name: 'Naan', price: 150, category: 'Snacks & Sides', recipe: [{ stockItemId: 'si_bread_slice', quantity: 1 }] },
  { id: 'ss12', name: 'Kachumbari', price: 150, category: 'Snacks & Sides', recipe: [] },
  { id: 'ss13', name: 'Kale (Sukuma)', price: 200, category: 'Snacks & Sides', recipe: [] },
  { id: 'ss14', name: 'Coconut Spinach', price: 200, category: 'Snacks & Sides', recipe: [] },
  { id: 'ss15', name: 'Ugali', price: 200, category: 'Snacks & Sides', recipe: [{ stockItemId: 'si_ugali_flour', quantity: 1 }] },
  { id: 'ss16', name: 'Mashed Potatoes', price: 200, category: 'Snacks & Sides', recipe: [{ stockItemId: 'si_potato', quantity: 250 }] },
  { id: 'ss17', name: 'Ugali Wimbi', price: 200, category: 'Snacks & Sides', recipe: [{ stockItemId: 'si_ugali_flour', quantity: 1 }] },
  { id: 'ss18', name: 'Managu', price: 200, category: 'Snacks & Sides', recipe: [] },
  { id: 'ss19', name: 'Mukimo', price: 200, category: 'Snacks & Sides', recipe: [] },
  { id: 'ss20', name: 'Matoke', price: 250, category: 'Snacks & Sides', recipe: [] },
  { id: 'ss21', name: 'Matumbo', price: 300, category: 'Snacks & Sides', recipe: [] },
  { id: 'ss22', name: 'Githeri', price: 200, category: 'Snacks & Sides', recipe: [] },
  { id: 'ss23', name: 'Extra Avocado', price: 100, category: 'Snacks & Sides', recipe: [{ stockItemId: 'si_avocado', quantity: 1 }] },
  { id: 'ss24', name: 'Extra 2 Boiled Eggs', price: 200, category: 'Snacks & Sides', recipe: [{ stockItemId: 'si_egg', quantity: 2 }] },
  { id: 'ss25', name: 'Extra Grilled Chicken', price: 300, category: 'Snacks & Sides', recipe: [{ stockItemId: 'si_chicken_breast', quantity: 1 }] },
  { id: 'ss26', name: 'Extra 2 Beef Sausages', price: 250, category: 'Snacks & Sides', recipe: [{ stockItemId: 'si_sausage_beef', quantity: 2 }] },
  { id: 'ss27', name: 'Extra Beef Bacon', price: 250, category: 'Snacks & Sides', recipe: [{ stockItemId: 'si_bacon_slice', quantity: 3 }] },
  { id: 'ss28', name: 'Extra Caramelised Onions', price: 120, category: 'Snacks & Sides', recipe: [{ stockItemId: 'si_onion', quantity: 50 }] },
  { id: 'ss29', name: 'Extra Cheese', price: 250, category: 'Snacks & Sides', recipe: [{ stockItemId: 'si_cheese', quantity: 1 }] },
  { id: 'ss30', name: 'Extra Toast', price: 120, category: 'Snacks & Sides', recipe: [{ stockItemId: 'si_bread_slice', quantity: 2 }] },

  // Platters
  { id: 'pl01', name: 'Savoury Brunch Platter', price: 1500, category: 'Platters', recipe: [{ stockItemId: 'si_platter_base', quantity: 2 }] },
  { id: 'pl02', name: 'Sweet Brunch Platter', price: 2000, category: 'Platters', recipe: [{ stockItemId: 'si_platter_base', quantity: 2 }] },
  { id: 'pl03', name: 'Platter For 2', price: 1950, category: 'Platters', recipe: [{ stockItemId: 'si_platter_base', quantity: 2 }] },
  { id: 'pl04', name: 'Platter For 3', price: 2550, category: 'Platters', recipe: [{ stockItemId: 'si_platter_base', quantity: 3 }] },
  { id: 'pl05', name: 'Platter For 4', price: 3550, category: 'Platters', recipe: [{ stockItemId: 'si_platter_base', quantity: 4 }] },
  { id: 'pl06', name: 'Platter For 5', price: 4250, category: 'Platters', recipe: [{ stockItemId: 'si_platter_base', quantity: 5 }] },
  { id: 'pl07', name: 'Platter For 6', price: 5200, category: 'Platters', recipe: [{ stockItemId: 'si_platter_base', quantity: 6 }] },
  
  // Kids Menu
  { id: 'km01', name: 'Kids Plain Pancake', price: 570, category: 'Kids Menu', recipe: [{ stockItemId: 'si_pancake_mix', quantity: 1 }] },
  { id: 'km02', name: 'Kids Pancake & Eggs', price: 570, category: 'Kids Menu', recipe: [{ stockItemId: 'si_pancake_mix', quantity: 1 }, { stockItemId: 'si_egg', quantity: 1 }] },
  { id: 'km03', name: 'Kids Pancake & Sausage', price: 610, category: 'Kids Menu', recipe: [{ stockItemId: 'si_pancake_mix', quantity: 1 }, { stockItemId: 'si_sausage_beef', quantity: 1 }] },
  { id: 'km04', name: 'Kids Fries & Sausage', price: 340, category: 'Kids Menu', recipe: [{ stockItemId: 'si_potato', quantity: 150 }, { stockItemId: 'si_sausage_beef', quantity: 1 }] },
  { id: 'km05', name: 'Kids Chicken Tenders', price: 500, category: 'Kids Menu', recipe: [{ stockItemId: 'si_chicken_tender', quantity: 3 }] },
  { id: 'km06', name: 'Kids Fish Fingers', price: 500, category: 'Kids Menu', recipe: [{ stockItemId: 'si_fish_finger', quantity: 4 }] },
  { id: 'km07', name: 'Kids Grilled Cheese', price: 640, category: 'Kids Menu', recipe: [{ stockItemId: 'si_bread_slice', quantity: 2 }, { stockItemId: 'si_cheese', quantity: 1 }] },
  { id: 'km08', name: 'Kids Cheese Burger', price: 640, category: 'Kids Menu', recipe: [{ stockItemId: 'si_burger_patty_beef', quantity: 1 }, { stockItemId: 'si_burger_bun', quantity: 1 }] },
  { id: 'km09', name: 'Kids Strawberry Milk', price: 200, category: 'Kids Menu', recipe: [{ stockItemId: 'si_milk', quantity: 200 }] },
  { id: 'km10', name: 'Kids Chocolate Milk', price: 200, category: 'Kids Menu', recipe: [{ stockItemId: 'si_milk', quantity: 200 }, { stockItemId: 'si_chocolate_powder', quantity: 10 }] },
  { id: 'km11', name: 'Kids Hot Chocolate', price: 220, category: 'Kids Menu', recipe: [{ stockItemId: 'si_milk', quantity: 200 }, { stockItemId: 'si_chocolate_powder', quantity: 15 }] },
  { id: 'km12', name: 'Kids Vanilla Milk', price: 200, category: 'Kids Menu', recipe: [{ stockItemId: 'si_milk', quantity: 200 }] },
  { id: 'km13', name: 'Kids Vanilla & Banana Smoothie', price: 300, category: 'Kids Menu', recipe: [{ stockItemId: 'si_smoothie_base', quantity: 1 }] },
  { id: 'km14', name: 'Kids Strawberry Smoothie', price: 300, category: 'Kids Menu', recipe: [{ stockItemId: 'si_smoothie_base', quantity: 1 }] },
  { id: 'km15', name: 'Kids Tropical Smoothie', price: 300, category: 'Kids Menu', recipe: [{ stockItemId: 'si_smoothie_base', quantity: 1 }] },
  { id: 'km16', name: 'Kids Fruit & Ice Cream', price: 420, category: 'Kids Menu', recipe: [{ stockItemId: 'si_ice_cream_scoop', quantity: 1 }] },
  { id: 'km17', name: 'Kids Chocolate Ice Cream', price: 210, category: 'Kids Menu', recipe: [{ stockItemId: 'si_ice_cream_scoop', quantity: 1 }] },
  { id: 'km18', name: 'Kids Vanilla Ice Cream', price: 210, category: 'Kids Menu', recipe: [{ stockItemId: 'si_ice_cream_scoop', quantity: 1 }] },

  // Desserts & Pastries
  { id: 'dp01', name: 'Tiramisu', price: 490, category: 'Desserts & Pastries', recipe: [{ stockItemId: 'si_dessert_slice', quantity: 1 }] },
  { id: 'dp02', name: 'Date Cake', price: 590, category: 'Desserts & Pastries', recipe: [{ stockItemId: 'si_dessert_slice', quantity: 1 }] },
  { id: 'dp03', name: 'Umm Ali', price: 590, category: 'Desserts & Pastries', recipe: [{ stockItemId: 'si_dessert_slice', quantity: 1 }] },
  { id: 'dp04', name: 'Brownie Cheesecake', price: 590, category: 'Desserts & Pastries', recipe: [{ stockItemId: 'si_dessert_slice', quantity: 1 }] },
  { id: 'dp05', name: 'Butter Croissant', price: 250, category: 'Desserts & Pastries', recipe: [{ stockItemId: 'si_croissant', quantity: 1 }] },
  { id: 'dp06', name: 'Almond Croissant', price: 250, category: 'Desserts & Pastries', recipe: [{ stockItemId: 'si_croissant', quantity: 1 }] },
  { id: 'dp07', name: 'Chocolate Croissant', price: 200, category: 'Desserts & Pastries', recipe: [{ stockItemId: 'si_croissant', quantity: 1 }] },
  { id: 'dp08', name: 'Carrot Cake', price: 300, category: 'Desserts & Pastries', recipe: [{ stockItemId: 'si_dessert_slice', quantity: 1 }] },
  { id: 'dp09', name: 'Black Forest Cake', price: 300, category: 'Desserts & Pastries', recipe: [{ stockItemId: 'si_dessert_slice', quantity: 1 }] },
  { id: 'dp10', name: 'Ice Cream (Vanilla, Single)', price: 250, category: 'Desserts & Pastries', recipe: [{ stockItemId: 'si_ice_cream_scoop', quantity: 1 }] },
  { id: 'dp11', name: 'Ice Cream (Vanilla, Double)', price: 450, category: 'Desserts & Pastries', recipe: [{ stockItemId: 'si_ice_cream_scoop', quantity: 2 }] },
  { id: 'dp12', name: 'Ice Cream (Chocolate, Single)', price: 250, category: 'Desserts & Pastries', recipe: [{ stockItemId: 'si_ice_cream_scoop', quantity: 1 }] },
  { id: 'dp13', name: 'Ice Cream (Chocolate, Double)', price: 450, category: 'Desserts & Pastries', recipe: [{ stockItemId: 'si_ice_cream_scoop', quantity: 2 }] },
  { id: 'dp14', name: 'Ice Cream (Strawberry, Single)', price: 250, category: 'Desserts & Pastries', recipe: [{ stockItemId: 'si_ice_cream_scoop', quantity: 1 }] },
  { id: 'dp15', name: 'Ice Cream (Strawberry, Double)', price: 450, category: 'Desserts & Pastries', recipe: [{ stockItemId: 'si_ice_cream_scoop', quantity: 2 }] },
  
  // Cold Drinks
  { id: 'cd01', name: 'Berry me Mojito', price: 600, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_mojito_base', quantity: 1 }] },
  { id: 'cd02', name: 'Kiwi Mojito', price: 600, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_mojito_base', quantity: 1 }] },
  { id: 'cd03', name: 'Blueberry Mojito', price: 600, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_mojito_base', quantity: 1 }] },
  { id: 'cd04', name: 'Passion Mojito', price: 600, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_mojito_base', quantity: 1 }] },
  { id: 'cd05', name: 'Peach Mojito', price: 600, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_mojito_base', quantity: 1 }] },
  { id: 'cd06', name: 'Mint Lemonade', price: 450, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_lemonade_base', quantity: 1 }] },
  { id: 'cd07', name: 'Passion Lemonade', price: 450, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_lemonade_base', quantity: 1 }] },
  { id: 'cd08', name: 'Classic Lemonade', price: 450, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_lemonade_base', quantity: 1 }] },
  { id: 'cd09', name: 'Strawberry Lemonade', price: 450, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_lemonade_base', quantity: 1 }] },
  { id: 'cd10', name: 'Blueberry Lemonade', price: 450, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_lemonade_base', quantity: 1 }] },
  { id: 'cd11', name: 'Peach Lemonade', price: 450, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_lemonade_base', quantity: 1 }] },
  { id: 'cd12', name: 'Kiwi Lemonade', price: 450, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_lemonade_base', quantity: 1 }] },
  { id: 'cd13', name: 'Tropical Smoothie', price: 550, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_smoothie_base', quantity: 1 }] },
  { id: 'cd14', name: 'Blueberry Smoothie', price: 550, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_smoothie_base', quantity: 1 }] },
  { id: 'cd15', name: 'Banana Mango Smoothie', price: 550, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_smoothie_base', quantity: 1 }] },
  { id: 'cd16', name: 'Strawberry Smoothie', price: 550, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_smoothie_base', quantity: 1 }] },
  { id: 'cd17', name: 'Avocado Shake', price: 550, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_milkshake_base', quantity: 1 }] },
  { id: 'cd18', name: 'Tropical Shake', price: 550, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_milkshake_base', quantity: 1 }] },
  { id: 'cd19', name: 'Hydrabad Shake', price: 550, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_milkshake_base', quantity: 1 }] },
  { id: 'cd20', name: 'Datte Shake', price: 550, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_milkshake_base', quantity: 1 }] },
  { id: 'cd21', name: 'Espresso Shake', price: 550, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_milkshake_base', quantity: 1 }, { stockItemId: 'si_coffee_beans', quantity: 10 }] },
  { id: 'cd22', name: 'Pineapple Juice', price: 400, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_juice_base', quantity: 1 }] },
  { id: 'cd23', name: 'Water Melon Juice', price: 400, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_juice_base', quantity: 1 }] },
  { id: 'cd24', name: 'Passion Juice', price: 400, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_juice_base', quantity: 1 }] },
  { id: 'cd25', name: 'Cocktail Juice', price: 400, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_juice_base', quantity: 1 }] },
  { id: 'cd26', name: 'Orange Juice', price: 400, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_juice_base', quantity: 1 }] },
  { id: 'cd27', name: 'Pineapple Mint Juice', price: 450, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_juice_base', quantity: 1 }] },
  { id: 'cd28', name: 'Water (Still, 300ml)', price: 150, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_water_still_300', quantity: 1 }] },
  { id: 'cd29', name: 'Water (Still, 500ml)', price: 250, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_water_still_500', quantity: 1 }] },
  { id: 'cd30', name: 'Water (Sparkling, 300ml)', price: 110, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_water_sparkling_300', quantity: 1 }] },
  { id: 'cd31', name: 'Water (Sparkling, 500ml)', price: 170, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_water_sparkling_500', quantity: 1 }] },
  { id: 'cd32', name: 'Soda (300ml)', price: 100, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_soda_300', quantity: 1 }] },
  { id: 'cd33', name: 'Soda (500ml)', price: 150, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_soda_500', quantity: 1 }] },
  { id: 'cd34', name: 'Iced Americano', price: 350, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_coffee_beans', quantity: 15 }] },
  { id: 'cd35', name: 'Iced Cappuccino', price: 350, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_coffee_beans', quantity: 15 }, { stockItemId: 'si_milk', quantity: 100 }] },
  { id: 'cd36', name: 'Iced Latte', price: 350, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_coffee_beans', quantity: 15 }, { stockItemId: 'si_milk', quantity: 150 }] },
  { id: 'cd37', name: 'Strawberry Iced Tea', price: 350, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_tea_leaves', quantity: 5 }] },
  { id: 'cd38', name: 'Passion Iced Tea', price: 350, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_tea_leaves', quantity: 5 }] },
  { id: 'cd39', name: 'Vanilla Iced Tea', price: 350, category: 'Cold Drinks', recipe: [{ stockItemId: 'si_tea_leaves', quantity: 5 }] },
];
